// Cross-language drift gate for the two facts this feature hand-mirrors from
// the Go engine:
//
//   - variantRules.ts   mirrors game.RulesFor's presets
//   - declarations.ts   mirrors game.detectDeclarations
//
// Both files declare themselves mirrors in prose, and until this test existed
// the only enforcement was two independently hand-written suites on each side:
// flipping a preset in RulesFor, or changing the one-card-one-group dedup,
// failed nothing here. The goldens are owned and regenerated by
// server/internal/game/rules_contract_test.go (UPDATE_GOLDENS=1) and read
// read-only from this side, exactly like the ws event goldens.
//
// Nothing is serialized to a client at runtime by this — VariantRules stays
// `json:"-"`. This is a build-time contract only.

import { describe, expect, it } from "vitest";

import type { Card, Rank, Suit } from "@/shared/types/matchTypes";

import declarationMeldsGolden from "../../../../../server/internal/game/testdata/contract/declaration_melds.json";
import variantRulesGolden from "../../../../../server/internal/game/testdata/contract/variant_rules.json";
import { detectDeclarations } from "./declarations";
import { rulesForVariant } from "./variantRules";

function parseHand(ids: string[]): Card[] {
  return ids.map((id) => ({ rank: id[0] as Rank, suit: id[1] as Suit }));
}

function toCardIds(cards: Card[]): string[] {
  return cards.map((c) => `${c.rank}${c.suit}`);
}

describe("variantRules.ts mirrors game.RulesFor", () => {
  it.each(["bitola", "croatia"] as const)(
    "%s declarationOverlap matches the Go preset",
    (variant) => {
      expect(rulesForVariant(variant).declarationOverlap).toBe(
        variantRulesGolden[variant].declarationOverlap,
      );
    },
  );

  it("the two variants genuinely differ on overlap", () => {
    // Guards against a golden that silently collapsed to one value, which would
    // make the per-variant assertions above pass without proving anything.
    expect(variantRulesGolden.bitola.declarationOverlap).toBe(false);
    expect(variantRulesGolden.croatia.declarationOverlap).toBe(true);
  });

  it("flags any Go rule field the client does not yet mirror", () => {
    // Informational, not a failure: the client deliberately mirrors only what
    // the UI reads. But when a NEW field appears in the Go preset, whoever adds
    // it should decide consciously whether the client needs it — so pin the
    // known set and make an addition surface here.
    expect(Object.keys(variantRulesGolden.bitola).sort()).toEqual([
      "allPassOutcome",
      "dealShape",
      "declarationOverlap",
      "declarationTiming",
      "hasTrumpCandidate",
      "revealFaceDownOnRound2",
      "tieRule",
    ]);
  });
});

describe("declarations.ts mirrors game.detectDeclarations", () => {
  it.each(declarationMeldsGolden.map((c) => [c.name, c] as const))(
    "%s — reproduces the Go melds under both overlap settings",
    (_name, c) => {
      const hand = parseHand(c.hand);

      const withoutOverlap = detectDeclarations(hand, false).map((d) => ({
        type: d.type,
        value: d.value,
        cards: toCardIds(d.cards),
      }));
      expect(withoutOverlap).toEqual(c.withoutOverlap);

      const withOverlap = detectDeclarations(hand, true).map((d) => ({
        type: d.type,
        value: d.value,
        cards: toCardIds(d.cards),
      }));
      expect(withOverlap).toEqual(c.withOverlap);
    },
  );

  it("the golden actually exercises the overlap divergence", () => {
    // If every case produced identical sets under both settings, the suite
    // above would pass while proving nothing about the Story 12.5 rule.
    const diverging = declarationMeldsGolden.filter(
      (c) => JSON.stringify(c.withoutOverlap) !== JSON.stringify(c.withOverlap),
    );
    expect(diverging.length).toBeGreaterThan(0);
  });
});
